// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>WebMinFin.ModelArrayGraphQl</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WebMinFin.ModelArrayGraphQl
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    /// <summary>
    /// Внутренняя модель отчетов с сайта МИНФИН
    /// </summary>
    public partial class ReportModel
    {

        public AllProject AllProject { get; set; }

        public Versions Versions { get; set; }

        public Tasks Tasks { get; set; }

        public checkpointExec checkpointExec { get; set; }

    }

    /// <summary>
    /// Все проекты
    /// </summary>
    public partial class AllProject
    {

        public int id { get; set; }

        public string name { get; set; }

        public string code { get; set; }

        public System.Nullable<System.DateTime> started { get; set; }

        public System.Nullable<System.DateTime> finished { get; set; }

        public string dictProjectStageName { get; set; }

        public string dictProjectStateName { get; set; }

        public string leadOrganizations { get; set; }

        public string versionNumber { get; set; }

        public bool isBlockedToEdit { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Версии карточки
    /// </summary>
    public partial class Versions
    {

        private List<editions> editionsField;

        private List<object> archivedEditionsField;

        public int id { get; set; }

        public string versionNumber { get; set; }

        public string number { get; set; }

        public string actualityPeriod { get; set; }

        public System.Nullable<int> projectId { get; set; }

        public bool versionIsActual { get; set; }

        public budgetCycle budgetCycle { get; set; }


        public List<editions> editions
        {
            get
            {
                return this.editionsField;
            }
            set
            {
                this.editionsField = value;
            }
        }

        public List<object> archivedEditions
        {
            get
            {
                return this.archivedEditionsField;
            }
            set
            {
                this.archivedEditionsField = value;
            }
        }
    }

    /// <summary>
    /// Редакторы
    /// </summary>
    public partial class editions
    {

        public int id { get; set; }

        public System.DateTime changeDate { get; set; }

        public string changeSetNumber { get; set; }

        public string createAuthor { get; set; }

        public System.DateTime createDate { get; set; }

        public string name { get; set; }

        public System.Nullable<int> projectId { get; set; }

        public kind kind { get; set; }

        public budgetCycle budgetCycle { get; set; }

        public string createType { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Отметка об исполнении
    /// </summary>
    public partial class kind
    {

        public int id { get; set; }

        public string name { get; set; }

        public string shortName { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Цыкл бюджета
    /// </summary>
    public partial class budgetCycle
    {

        public int id { get; set; }

        public string name { get; set; }

        public int startYear { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Задания на сайте министерства финансов
    /// </summary>
    public partial class Tasks
    {

        private List<results> resultsField;

        public int id { get; set; }

        public string name { get; set; }

        public string __typename { get; set; }


        public List<results> results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }

    /// <summary>
    /// Результаты
    /// </summary>
    public partial class results
    {

        private List<values> valuesField;

        public int id { get; set; }

        public string name { get; set; }

        public string responsibleExecutor { get; set; }

        public System.Nullable<bool> isMonetary { get; set; }

        public string bpOkeiName { get; set; }

        public string versionMetaId { get; set; }

        public string dataSource { get; set; }

        public System.Nullable<int> executionsCount { get; set; }

        public string unpResultTypeCode { get; set; }

        public execution execution { get; set; }

        public string autocreateValue { get; set; }

        public string __typename { get; set; }


        public List<values> values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <summary>
    /// Исполнение
    /// </summary>
    public partial class execution
    {

        public int id { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string status { get; set; }

        public string number { get; set; }

        public string achievementStatus { get; set; }

        public string statusType { get; set; }

        public string type { get; set; }

        public string period { get; set; }

        public string dictProjectStageName { get; set; }

        public string dictProjectStateName { get; set; }

        public System.Nullable<int> parentId { get; set; }

        public System.Nullable<bool> isAutoCreate { get; set; }

        public System.Nullable<bool> manualEdit { get; set; }

        public System.Nullable<bool> prove { get; set; }

        public System.Nullable<bool> serviceExpired { get; set; }

        public System.Nullable<bool> serviceForecast { get; set; }

        public System.Nullable<bool> isHaveDocuments { get; set; }

        public System.Nullable<int> dictProjectStateId { get; set; }

        public System.Nullable<int> dictProjectStageId { get; set; }

        public System.Nullable<System.DateTime> approvalDate { get; set; }

        public System.Nullable<bool> canSendForApproval { get; set; }

        public string __typename { get; set; }

        public System.Nullable<System.DateTime> date { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified { get; set; }

    }

    /// <summary>
    /// Значения
    /// </summary>
    public partial class values
    {

        private List<monthlyValues> monthlyValuesField;

        private List<checkpoints> checkpointsField;

        private List<objects> objectsField;

        public int id { get; set; }

        public string name { get; set; }

        public string resultName { get; set; }

        public System.Nullable<double> value { get; set; }

        public string responsibleExecutor { get; set; }

        public System.Nullable<System.DateTime> date { get; set; }

        public string versionMetaId { get; set; }

        public System.Nullable<System.DateTime> plannedDate { get; set; }

        public string autocreateValue { get; set; }

        public System.Nullable<bool> canEditExecution { get; set; }

        public System.Nullable<bool> canDeleteExecution { get; set; }

        public System.Nullable<bool> canAddExecution { get; set; }

        public int resultValueYear { get; set; }

        public System.Nullable<bool> needFinSourceWarning { get; set; }

        public System.Nullable<int> indicatorDynamics { get; set; }

        public tooltipInfo tooltipInfo { get; set; }

        public System.Nullable<int> executionsCount { get; set; }

        public execution execution { get; set; }


        public List<monthlyValues> monthlyValues
        {
            get
            {
                return this.monthlyValuesField;
            }
            set
            {
                this.monthlyValuesField = value;
            }
        }

        public List<checkpoints> checkpoints
        {
            get
            {
                return this.checkpointsField;
            }
            set
            {
                this.checkpointsField = value;
            }
        }

        public List<objects> objects
        {
            get
            {
                return this.objectsField;
            }
            set
            {
                this.objectsField = value;
            }
        }
    }

    /// <summary>
    /// Значение месяца планирования
    /// </summary>
    public partial class monthlyValues
    {

        public System.Nullable<int> month { get; set; }

        public System.Nullable<double> planValue { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Информирующий интрумент
    /// </summary>
    public partial class tooltipInfo
    {

        public string addExecutionButton { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Точки Checkpoint
    /// </summary>
    public partial class checkpoints
    {

        public int id { get; set; }

        public string name { get; set; }

        public System.Nullable<System.DateTime> date { get; set; }

        public System.Nullable<double> value { get; set; }

        public string responsibleExecutor { get; set; }

        public string ktTypeDisplayName { get; set; }

        public string bpOkeiName { get; set; }

        public string dataSource { get; set; }

        public string type { get; set; }

        public string versionMetaId { get; set; }

        public System.Nullable<System.DateTime> plannedDate { get; set; }

        public int unpKtTypeId { get; set; }

        public string autocreateValue { get; set; }

        public System.Nullable<bool> canEditExecution { get; set; }

        public System.Nullable<bool> canDeleteExecution { get; set; }

        public System.Nullable<bool> canAddExecution { get; set; }

        public tooltipInfo tooltipInfo { get; set; }

        public System.Nullable<int> executionsCount { get; set; }

        public execution execution { get; set; }

        public string __typename { get; set; }

    }

    /// <summary>
    /// Объекты
    /// </summary>
    public partial class objects
    {

        private List<checkpoints> checkpointsField;

        public int id { get; set; }

        public string name { get; set; }

        public System.Nullable<double> value { get; set; }

        public string responsibleExecutor { get; set; }

        public System.Nullable<System.DateTime> date { get; set; }

        public string versionMetaId { get; set; }

        public string bpOkeiName { get; set; }

        public string dataSource { get; set; }

        public System.Nullable<bool> canEditExecution { get; set; }

        public System.Nullable<bool> canDeleteExecution { get; set; }

        public System.Nullable<bool> canAddExecution { get; set; }

        public tooltipInfo tooltipInfo { get; set; }

        public System.Nullable<int> executionsCount { get; set; }

        public execution execution { get; set; }

        public string autocreateValue { get; set; }

        public string __typename { get; set; }


        public List<checkpoints> checkpoints
        {
            get
            {
                return this.checkpointsField;
            }
            set
            {
                this.checkpointsField = value;
            }
        }
    }

    /// <summary>
    /// Контрольная точка выполнение
    /// </summary>
    public partial class checkpointExec
    {

        private List<sbyte> documentsField;

        public int id { get; set; }

        public System.Nullable<double> planValue { get; set; }

        public System.Nullable<int> factValue { get; set; }

        public System.Nullable<System.DateTime> endDate { get; set; }

        public System.Nullable<System.DateTime> executionDate { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string type { get; set; }

        public string achievementStatus { get; set; }

        public string status { get; set; }

        public string number { get; set; }

        public string statusType { get; set; }

        public string documentType { get; set; }

        public object comment { get; set; }

        public string additionalInformation { get; set; }

        public string dictProjectStageName { get; set; }

        public string dictProjectStateName { get; set; }

        public string reasonOfEdit { get; set; }

        public bpAgreementsInformation bpAgreementsInformation { get; set; }

        public string __typename { get; set; }


        public List<sbyte> documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    /// <summary>
    /// Информация о соглашении
    /// </summary>
    public partial class bpAgreementsInformation
    {

        public System.Nullable<int> totalAgreementSum { get; set; }

        public System.Nullable<int> totalLboSum { get; set; }

        public System.Nullable<int> reportCountPlan { get; set; }

        public System.Nullable<int> providedReportCount { get; set; }

        public System.Nullable<int> unprovidedReportCount { get; set; }

        public System.Nullable<int> approvedGz { get; set; }

        public System.Nullable<int> subjectCount { get; set; }

        public System.Nullable<int> agreementConclusionCount { get; set; }

        public System.Nullable<int> agreementRejectedCount { get; set; }

        public System.Nullable<int> agreementNotConclusionCount { get; set; }

        public System.Nullable<System.DateTime> reportMaxDate { get; set; }

        public string reasonDocuments { get; set; }

        public string __typename { get; set; }

    }
}
