// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>WebMinFin.ModelEditAndAdd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WebMinFin.ModelEditAndAdd
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ModelEditWeb
    {

        public data data { get; set; }

        public variables variables { get; set; }

        public File File { get; set; }

    }

    public partial class data
    {

        public executions executions { get; set; }

    }

    public partial class executions
    {

        public checkpointExec checkpointExec { get; set; }

        public resultValueExec resultValueExec { get; set; }

        public workPlanObjectExec workPlanObjectExec { get; set; }

        public object __typename { get; set; }

    }

    public partial class checkpointExec
    {

        private List<documents> documentsField;

        public System.Nullable<int> id { get; set; }

        public System.Nullable<float> planValue { get; set; }

        public System.Nullable<int> factValue { get; set; }

        public System.Nullable<System.DateTime> endDate { get; set; }

        public System.Nullable<System.DateTime> executionDate { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string type { get; set; }

        public string achievementStatus { get; set; }

        public string status { get; set; }

        public string number { get; set; }

        public string statusType { get; set; }

        public string documentType { get; set; }

        public string comment { get; set; }

        public string additionalInformation { get; set; }

        public object dictProjectStageName { get; set; }

        public object dictProjectStateName { get; set; }

        public object reasonOfEdit { get; set; }

        public bpAgreementsInformation bpAgreementsInformation { get; set; }

        public object __typename { get; set; }


        public List<documents> documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    public partial class documents
    {

        private List<int> fileIdListField;

        private List<object> filesField;

        public System.Nullable<int> id { get; set; }

        public object name { get; set; }

        public string number { get; set; }

        public string date { get; set; }

        public System.Nullable<long> npaKindId { get; set; }

        public string link { get; set; }

        public string authorDepartmentName { get; set; }

        public System.Nullable<bool> isDSP { get; set; }

        public System.Nullable<long> authorDepartmentId { get; set; }

        public string orderNumber { get; set; }

        public System.Nullable<int> bpFileId { get; set; }

        public npaKind npaKind { get; set; }

        public string authorDepartment { get; set; }

        public string authorDepartmentName1 { get; set; }

        public object __typename { get; set; }


        public List<int> fileIdList
        {
            get
            {
                return this.fileIdListField;
            }
            set
            {
                this.fileIdListField = value;
            }
        }

        public List<object> files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
    }

    public partial class npaKind
    {

        public System.Nullable<int> id { get; set; }

        public object name { get; set; }

        public object __typename { get; set; }

    }

    public partial class bpAgreementsInformation
    {

        private byte[][] reasonDocumentsField;

        public System.Nullable<int> totalAgreementSum { get; set; }

        public System.Nullable<int> totalLboSum { get; set; }

        public System.Nullable<int> reportCountPlan { get; set; }

        public System.Nullable<int> providedReportCount { get; set; }

        public System.Nullable<int> unprovidedReportCount { get; set; }

        public System.Nullable<int> approvedGz { get; set; }

        public System.Nullable<int> subjectCount { get; set; }

        public System.Nullable<int> agreementConclusionCount { get; set; }

        public System.Nullable<int> agreementRejectedCount { get; set; }

        public System.Nullable<int> agreementNotConclusionCount { get; set; }

        public System.Nullable<System.DateTime> reportMaxDate { get; set; }

        public object __typename { get; set; }


        public byte[][] reasonDocuments
        {
            get
            {
                return this.reasonDocumentsField;
            }
            set
            {
                this.reasonDocumentsField = value;
            }
        }
    }

    public partial class resultValueExec
    {

        private List<documents> documentsField;

        public System.Nullable<int> id { get; set; }

        public System.Nullable<float> planValue { get; set; }

        public System.Nullable<int> factValue { get; set; }

        public System.Nullable<int> forecastValue { get; set; }

        public System.Nullable<System.DateTime> endDate { get; set; }

        public System.Nullable<System.DateTime> executionDate { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string type { get; set; }

        public string achievementStatus { get; set; }

        public string status { get; set; }

        public string number { get; set; }

        public string statusType { get; set; }

        public string documentType { get; set; }

        public string comment { get; set; }

        public string additionalInformation { get; set; }

        public object dictProjectStageName { get; set; }

        public object dictProjectStateName { get; set; }

        public string dynamics { get; set; }

        public string warningMessage { get; set; }

        public object __typename { get; set; }


        public List<documents> documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    public partial class workPlanObjectExec
    {

        private List<documents> documentsField;

        public System.Nullable<int> id { get; set; }

        public System.Nullable<float> planValue { get; set; }

        public System.Nullable<int> factValue { get; set; }

        public System.Nullable<int> forecastValue { get; set; }

        public System.Nullable<System.DateTime> endDate { get; set; }

        public System.Nullable<System.DateTime> executionDate { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string type { get; set; }

        public string achievementStatus { get; set; }

        public string status { get; set; }

        public string number { get; set; }

        public string statusType { get; set; }

        public string documentType { get; set; }

        public string comment { get; set; }

        public string additionalInformation { get; set; }

        public object dictProjectStageName { get; set; }

        public object dictProjectStateName { get; set; }


        public List<documents> documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    public partial class variables
    {

        public request request { get; set; }

    }

    public partial class request
    {

        private List<documents> documentsField;

        public System.Nullable<int> factValue { get; set; }

        public System.Nullable<System.DateTime> executionDate { get; set; }

        public System.Nullable<int> delay { get; set; }

        public string type { get; set; }

        public string achievementStatus { get; set; }

        public string status { get; set; }

        public string statusType { get; set; }

        public System.Nullable<int> month { get; set; }

        public System.Nullable<int> year { get; set; }

        public string documentType { get; set; }

        public string comment { get; set; }

        public string additionalInformation { get; set; }

        public System.Nullable<int> id { get; set; }

        public System.Nullable<int> parentId { get; set; }

        public System.Nullable<bool> isAutoCreate { get; set; }

        public System.Nullable<bool> manualEdit { get; set; }

        public System.Nullable<bool> prove { get; set; }

        public System.Nullable<bool> serviceExpired { get; set; }

        public System.Nullable<bool> serviceForecast { get; set; }

        public System.Nullable<int> checkpointId { get; set; }

        public string projectKind { get; set; }

        public System.Nullable<int> forecastValue { get; set; }

        public System.Nullable<int> projectTaskResultValueId { get; set; }

        public System.Nullable<int> workPlanObjectId { get; set; }


        public List<documents> documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    public partial class File
    {

        public System.Nullable<int> id { get; set; }

        public object name { get; set; }

        public long size { get; set; }

        public object url { get; set; }

    }
}
