// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>WebMinFin.FullWebGlobalModelGraphQl</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WebMinFin.FullWebGlobalModelGraphQl
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class GlobalModelWeb<T>
    {

        public departmentalProject<T> departmentalProject { get; set; }

        public executionMonitoring<T> executionMonitoring { get; set; }

        public modelEdit<T> modelEdit { get; set; }

    }

    public partial class departmentalProject<T>
    {

        public string __typename { get; set; }

        public list<T> list { get; set; }

        public card<T> card { get; set; }

    }

    public partial class list<T>
    {

        public string __typename { get; set; }

        public T data { get; set; }

        public pagination pagination { get; set; }

    }

    public partial class pagination
    {

        public int total { get; set; }

        public int left { get; set; }

        public string __typename { get; set; }

    }

    public partial class card<T>
    {

        private List<string> allowedTabsField;

        private List<string> editYearsField;

        private List<string> nationalDevelopmentYearsField;

        public System.Nullable<int> id { get; set; }

        public string name { get; set; }

        public System.DateTime started { get; set; }

        public System.DateTime finished { get; set; }

        public string projectCode { get; set; }

        public System.Nullable<bool> isBlockedToEdit { get; set; }

        public System.Nullable<bool> isBlockedToCreateEdition { get; set; }

        public string dictProjectStateName { get; set; }

        public T versions { get; set; }

        public string versionNumber { get; set; }

        public string versionId { get; set; }

        public System.Nullable<bool> isVersion { get; set; }

        public System.Nullable<int> changeSetKindId { get; set; }

        public System.Nullable<bool> isCanSyncResultsWithEsr { get; set; }

        public System.Nullable<bool> isPrimaryVersion { get; set; }

        public budgetCycle budgetCycle { get; set; }

        public string __typename { get; set; }


        public List<string> allowedTabs
        {
            get
            {
                return this.allowedTabsField;
            }
            set
            {
                this.allowedTabsField = value;
            }
        }

        public List<string> editYears
        {
            get
            {
                return this.editYearsField;
            }
            set
            {
                this.editYearsField = value;
            }
        }

        public List<string> nationalDevelopmentYears
        {
            get
            {
                return this.nationalDevelopmentYearsField;
            }
            set
            {
                this.nationalDevelopmentYearsField = value;
            }
        }
    }

    public partial class budgetCycle
    {

        public System.Nullable<int> id { get; set; }

        public string name { get; set; }

        public System.Nullable<int> startYear { get; set; }

        public string __typename { get; set; }

    }

    public partial class executionMonitoring<T>
    {

        public tree<T> tree { get; set; }

    }

    public partial class tree<T>
    {

        public lastReportForPeriodInfo lastReportForPeriodInfo { get; set; }

        public T tasks { get; set; }

        public string __typename { get; set; }

    }

    public partial class lastReportForPeriodInfo
    {

        public System.Nullable<int> id { get; set; }

        public System.Nullable<int> dictProjectStateId { get; set; }

        public System.Nullable<int> dictProjectStageId { get; set; }

        public System.Nullable<System.DateTime> approvalDate { get; set; }

        public string __typename { get; set; }

    }

    public partial class modelEdit<T>
    {

        public T executions { get; set; }

        public string __typename { get; set; }

    }
}
